/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package PersonalBookstoreProject;

/**
 * Paid premium class with discount
 *
 * @author Ethan Herring
 */
public class PremiumMember extends Customers {

    boolean feePaid;
    int lastFourOfCard;

    /**
     * Seperates premium member based from customer class
     *
     * @param name customer name
     * @param birthday customer birthday
     * @param email customer email
     * @param totalSpent total spent over time
     * @param memberNumber autogenerated member id
     * @param feePaid tells if membership fee is paid
     * @param lastFourOfCard last 4 of card for membership payment
     */
    public PremiumMember(String name, String birthday, String email,
            double totalSpent, int memberNumber, boolean feePaid, int lastFourOfCard) {
        super(name, birthday, email, totalSpent, memberNumber);
        this.feePaid = feePaid;
        this.lastFourOfCard = lastFourOfCard;
    }

    /**
     * Sets fee to paid
     *
     * @return true if it is paid
     */
    public boolean setFeePaid() {
        feePaid = true;
        return true;
    }

    /**
     * determins rewards discount based on total spent
     *
     * @return discount amount
     */
    public double rewardsDiscount() {
        System.out.println("Thanks for being a premium member!");

        if (totalSpent <= 100) {
            return .05;
        } else if (totalSpent >= 100 && totalSpent <= 200) {
            return .15;
        } else if (totalSpent > 200) {
            return .20;
        }
        return 0;
    }
}
