/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package PersonalBookstoreProject;

import java.util.*;

/**
 * abstract parent class for book,cd,and dvd classes
 *
 * @author Ethan Herring
 */
public abstract class Products {

    private String name;
    private String author;
    private double price;
    private int stock;
    public static int productID = 0;
    private int barcode;
    private int numPurcahsed=0;

    /**
     * Parent class for books,dvd,and cd classes
     *
     * @param name product name
     * @param author product author
     * @param price product price
     * @param stock amount in stock
     * @param barcode autogenerated barcode
     */
    public Products(String name, String author, double price, int stock, int barcode) {
        this.name = name;
        this.author = author;
        this.price = price;
        this.stock = stock;
        this.barcode = barcode;
    }

    /**
     * Prints Name
     *
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets Name
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Prints Author
     *
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets Author
     *
     * @param author author
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Prints price
     *
     * @return price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets Price
     *
     * @param price price
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * gets amount in stock
     *
     * @return stock amount
     */
    public int getStock() {
        return stock;
    }

    /**
     * Sets stock amount
     *
     * @param stock amount in stock
     */
    public void setStock(int stock) {
        this.stock = stock;
    }

    /**
     * Prints barcode
     *
     * @return barcode
     */
    public int getBarcode() {
        return barcode;
    }

    /**
     * Incriments barcode
     *
     * @return next barcode
     */
    public int incrimentBarcode() {
        productID++;
        return productID;
    }

    /**
     * Compares two product prices
     *
     * @param o product to comapare
     * @return -1 if less than or 1 if greater than or 0 if equal
     */
    public int compareTo(Products o) {
        double oPrice = o.getPrice();
        double sPrice = this.getPrice();
        System.out.println("Price: " + sPrice + " and " + oPrice);
        if (oPrice > sPrice) {
            return 1;
        }
        if (oPrice < sPrice) {
            return -1;
        }

        return 0;
    }
    public void setNumberPurchased(int i){
        numPurcahsed=i;
    }public int getNumberPurchased(){
        return numPurcahsed;
    }


}
